### ISSUE TITLE
uncaught error after refresh page

### ISSUE THREAD

**Issue by dengjiuhong** [orgsync/react-list#132]
invariant.js?4599:38 Uncaught Invariant Violation: findDOMNode was called on an unmounted component

![snip20160825_25](https://cloud.githubusercontent.com/assets/22500/17976400/e590ff30-6b1f-11e6-8d21-a34c727b0330.png)

**Comment by caseywebdev** [comment]
This might be related to #131 and the event handlers not being deregistered properly.

**Comment by dengjiuhong** [comment]
thanks, problem have been solved.
nice components! good job!

**Comment by caseywebdev** [comment]
So is it safe to close this issue?

**Comment by theopolisme** [comment]
Dup of #121 - think it's probably safe to close that too.

**Comment by NeXTs** [comment]
still seeing this issue sometimes
as I noticed it occurs when user leaves page where react-list was used
